### ISSUE TITLE
Support PWA mode for mobile use

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#108]
Some users may want to run this app as PWA on mobile and create an icon for quick access.

AFAIK all we need to do is to add some headers/manifests:

> Manifest files are [supported](https://developer.mozilla.org/en-US/docs/Web/Manifest#Browser_compatibility) in Chrome, Edge, Firefox, UC Browser, Opera, and the Samsung browser. Safari has partial support

- https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs
- https://web.dev/progressive-web-apps
  - https://web.dev/install-criteria/
  - https://web.dev/add-manifest/
- https://github.com/gokulkrishh/awesome-meta-and-manifest

Thoughts?

**Comment by jessicaschilling** [comment]
Small but useful. @rafaelramalho19 are you able to take this one today? 🙏
