### ISSUE TITLE
Unified padding

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#109]
Not sure if it is a bug or feature, but I feel things would look better if the padding was the same on both sides of number.

Right now (4232cbb0b6a82bcf167ef09a20475cccd16b60a9) looks like this:

> ![2021-02-04--18-04-59](https://user-images.githubusercontent.com/157609/106928634-ad08b280-6713-11eb-83d7-aa054e71b00b.png)

**Comment by jessicaschilling** [comment]
It's vertically centered on the text div to its right. Not perfect, but minimizes awkwardness across a variety of widths. Request that we close this issue.
