### ISSUE TITLE
not support user didn't install/start ipfs now?

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-share-files#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

like old version, a js-ipfs for who didn't has ipfs

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/167966/107859465-8dd8f600-6e74-11eb-9d55-137da6ab1c91.png)

**Comment by jessicaschilling** [comment]
Try clearing all your caches.

**Comment by aschmahmann** [comment]
seems like this is resolved
