### ISSUE TITLE
header x-ipfs-path should include cid when it is a share cid page

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-share-files#130]
**Describe the bug**

**To Reproduce**

https://share.ipfs.io/#/bafybeihrqpj2nf5ldxw7bw55dn2kt24nxgjltx42eoxmbwjrgdlddrfivm

**Expected behavior**

x-ipfs-path include cid

**Screenshots**

![image](https://user-images.githubusercontent.com/167966/125564639-47995404-1f93-49b4-b549-85882139908a.png)

**Comment by lidel** [comment]
No, `x-ipfs-path` represents the content path of the resource fetched over HTTP.
In the screenshot you provided it is the address of the root document  for the website.
