### ISSUE TITLE
🆘 Needs maintainer

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ipfs-share-files#134]
This repo is marked as not having a maintainer and not being supported until it does. See https://github.com/protocol/bifrost-infra/issues/2018#issuecomment-1212366561

**Comment by hacdias** [comment]
Maybe we should do something similar for ipfs-shipyard/ipfs-deploy, as the idea of deprecating it seems to not be welcome: https://github.com/ipfs-shipyard/ipfs-deploy/issues/238 However, we really don't have bandwidth for it.
