### ISSUE TITLE
Gateway requests responds with `403 - Forbidden`

### ISSUE THREAD

**Issue by fsdiogo** [ipfs-shipyard/ipfs-share-files#17]
When in the `Download` page, the user shouldn't have to have an IPFS instance or daemon running, so we'll use the `ipfs.io` gateway to fetch the files and download them.

The problem here is that when making the request the response is always `403 - Forbidden`.
https://github.com/ipfs-shipyard/ipfs-share-files/blob/7ed1070796187f0079620e7b836f31b8e23c4dbb/src/pages/download/Download.js#L20

https://github.com/ipfs-shipyard/ipfs-share-files/blob/7ed1070796187f0079620e7b836f31b8e23c4dbb/src/bundles/files.js#L222-L248

Both in Postman or directly in the browser the response comes OK, but not in the app.

**Comment by fsdiogo** [comment]
@lidel yes!

Then use a valid hash and go to:

```sh
http://localhost:3000/#/<hash>
```

That will open the download page and send a request to the gateway.

**Comment by lidel** [comment]
I eyeballed failing (403) and standalone request (200):

![screenshot_17](https://user-images.githubusercontent.com/157609/44737371-18d1a480-aaf2-11e8-9793-a1781e6de4c0.png)


403 is triggered when either `Origin` or `Referrer` is present:

```console
$ curl 'https://ipfs.io/api/v0/ls?arg=QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR' 
{"Objects":[{"Hash":"QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR","Links":[]}]}

$ curl 'https://ipfs.io/api/v0/ls?arg=QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR' -H 'Origin: http://localhost:3000'
403 - Forbidden

$ curl 'https://ipfs.io/api/v0/ls?arg=QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR' -H 'Referer: http://localhost:3000/'
403 - Forbidden
```

AFAIK its the `fetch` API itself adding those in default mode.
Need to run afk for today, may look into it tomorrow.

**Comment by fsdiogo** [comment]
When sending the request to a local JS and Go daemon it succeeds.

As @lidel mentioned, it's probably some header check in the gateway that fails and returns 403.

I'll expose this to the `#ipfs-dev` IRC channel to get more feedback.

**Comment by lidel** [comment]
Actually its even more bizarre!
- `Origin: http://localhost:3000/` fails
- `Origin: http://localhost:8080` works fine

Keep in  mind we are talking about gateway at `ipfs.io`. It's either additional validation done in go-ipfs or some odd misconfiguration in nginx. 

```console
$ curl 'https://ipfs.io/api/v0/ls?arg=QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR' -H 'Origin: http://localhost:3000/'
403 - Forbidden

$ curl 'https://ipfs.io/api/v0/ls?arg=QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR' -H 'Origin: http://localhost:8080'
{"Objects":[{"Hash":"QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR","Links":[]}]
```

**Comment by fsdiogo** [comment]
Wow, thanks @lidel! It really is strange!

@lgierth can you please ping here when it is fixed?

**Comment by fsdiogo** [comment]
Huge thanks to @lidel and @lgierth, this is now fixed!
