### ISSUE TITLE
i18n: add to Transifex

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#33]
When https://github.com/ipfs-shipyard/ipfs-share-files/issues/10 is closed, we should have most of source text in place.

That will be good time to add this app to https://www.transifex.com/ipfs/public/ just like we did with IPLD Explorer. 

Ping me when ready, I'll do the setup in a PR :)

**Comment by fsdiogo** [comment]
Agreed and will do, thank you @lidel!
