### ISSUE TITLE
Clickable file names

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#49]
For some reason I find myself often clicking on file names and.. nothing happens. 

Here's an idea: 

![2018-11-23--14-08-18](https://user-images.githubusercontent.com/157609/48945067-4bd8d800-ef29-11e8-85f7-5f8fd9b9eb9a.png)

- Keep download icon ![screenshot_2018-11-23 48945067-4bd8d800-ef29-11e8-85f7-5f8fd9b9eb9a png png image 353 x 129 pixels](https://user-images.githubusercontent.com/157609/48945097-657a1f80-ef29-11e8-911c-402695a56f5e.png) as-is  
- **Make file names always link to item at the public gateway** 
  - Works the same for files and directories: just open gateway resource in a new tab (`target="_blank"`) 
  - On-hover title `Open in a new tab`
  - This enables people to dig into directories or copy a direct link to a file without leaving a page

Are there downsides to this?
Thoughts?

**Comment by olizilla** [comment]
@lidel oh my yes please. I really like keeping the option of opening things in a tab. The only tweak I'd suggest is opening on the local gateway where possible and using the public gateway where an embedded js-ipfs node is being used.

**Comment by fsdiogo** [comment]
I like this approach. It's an easy way to give users the ability to go through folders, as it's not possible to do it in-app.
