### ISSUE TITLE
Multiple "Error: Callback was already called" with js-ipfs fallback

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#50]
When js-ipfs fallback is used in Google Chrome v70 this happens in console
(as far I could tell, it does not seem to impact download):

![2018-11-25--01-36-28](https://user-images.githubusercontent.com/157609/48974242-087a8880-f053-11e8-8bf4-1aa36b4ae935.png)

## How to Replicate

- ensure js-ipfs fallback is used (disable ipfs-companion, shut down local IPFS Node)
- open https://share.ipfs.io/#/QmP9JvpGEAXCNUUWnZCFK1WzThTtTi6Te1oCyf47YVVEJz in Google 
- open console

## References

- This may be related to https://github.com/libp2p/js-libp2p-secio/issues/100 and https://github.com/ipfs/aegir/pull/214

**Comment by fsdiogo** [comment]
Thanks for the report and for pointing out the solution @lidel 😄

I've created a PR with the fix.
