### ISSUE TITLE
Illegible at narrow widths due to color contrast

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-shipyard/ipfs-share-files#54]
Feel free to ignore this if there's a reason no one will ever use this app on a narrow device, but when I look on my phone or adjust the width of my browser window I can't read the light gray text on the teal background. Perhaps the two-colored background should become just the navy-ish color when the screen is narrower?

![image](https://user-images.githubusercontent.com/19171465/49039217-20eebe00-f18d-11e8-952b-44d4399e15f3.png)

**Comment by fsdiogo** [comment]
As the current copy is temporary I haven't tweaked the responsiveness as it will possibly change a bit. Either way I'll fix it until we work on it 👍
