### ISSUE TITLE
Experiment with enabling WebRTC in js-ipfs fallback

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#58]
What if we enable WebRTC in fallback js-ipfs node?

In the past browsers had stability issues when js-ipfs run with webrtc transport for a long time.
We had various changes since then across the stack and the tab with share app will usually be closed after user is done with upload/download minimizing risk of it running for long enough to cause trouble.

Could WebRTC potentially..
- improve discovery and performance of sharing app
- give more merit to p2p claims made in copy/docs :)
- build better understanding of how stable WebRTC transport is today, identify pain points   and work towards addressing them in ipfs/libp2p/browser stack.

?

Refs:
- Stable transports in the browser -  https://github.com/ipfs/js-ipfs/issues/1088
  - Notes on IPFS+WebRTC tuning done by Paratii team - https://github.com/ipfs/js-ipfs/issues/1088#issuecomment-401555159
  - WebRTC ignoring(?) connection manager's limits - https://github.com/ipfs/js-ipfs/issues/1088#issuecomment-418938720

**Comment by olizilla** [comment]
I'm for this, but not yet. I think we need to make "understanding WebRTC limits and tuning" a high priority. I'd rather have us dedicate focused time to understandting the root causes of the problem and the effects of the tuning options before enabling it again on an app.

**Comment by lidel** [comment]
We switched to the latest js-ipfs where webrtc is enabled by default
