### ISSUE TITLE
Icon for copying direct link to individual file

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#59]
Feedback extracted from https://github.com/ipfs-shipyard/ipfs-share-files/issues/41#issuecomment-442103534:
>  I also don't see a way to go back and get a URL for just one of files if I only want to share one of them instead of the whole current batch. Is that possible and I'm missing how to do it? 

And https://github.com/ipfs-shipyard/ipfs-share-files/issues/41#issuecomment-442175082:
> Let's say I just added three files that Oli needs, and I successfully figured out that I needed to share the link after all three were there to give him access to all three (which hopefully I will after we add an explainer). An hour later I realize you need one of those files, but just one. It will annoy me to have to go and upload the same file I already uploaded in order to get it separate from the other two. The interface I'm accustomed to is something like Dropbox where I only have to upload a file once and then I can right click to grab/share a link to a specific file OR a folder of files whenever I want without spending more time uploading again. That limitation means I'll have to invest more work and keep more browser tabs open if I need to keep sharing similar things with a variety of people. This tool feels like it has the usefulness of a one-and-done service like Air Drop, not the long-term utility of a Dropbox, Box, Drive, etc. that's more versatile. If it's a real limitation in what can be accomplished with IPFS, that's fine, but if you could save the CID for that specific document and make it available without too much trouble, it would be a huge UX gain in my opinion.

@terichadbourne we recently made file names clickable, so you could context-click on file name and copy link that way.

I agree the UX for this is not intuitive and could be improved, eg. by adding an icon for one-click copying:

>  ![2018-11-27--23-11-41](https://user-images.githubusercontent.com/157609/49115001-e292f500-f299-11e8-9dd4-f0e77885b3de.png)

Would this help or only made things worse?

**Comment by terichadbourne** [comment]
I think what I actually tried to do when guessing at the UI was to right click that checkmark, so I think that solution would work for me. But I’d be equally happy with a note down below that makes it clear the main URL you’re being offered is for the folder and that you can click an individual file above to get a separate link for it. Glad to hear this is something one can do!

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-share-files/pull/89 is WIP and should take care of this.
