### ISSUE TITLE
Filename overflow glitch in Firefox

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#67]
Tried some files with tilling manager (custom window size) and longer names and this happened: 

![2018-12-17--01-32-11](https://user-images.githubusercontent.com/157609/50061011-af0e0100-019b-11e9-9f43-3be3db339b93.png)

It is possible its just an oddity in font handling on my machine, anyone is able to reproduce?

Just for the record, tested [this version from dnslink](https://ipfs.io/ipfs/QmPdh9FoRuP291f2NFffUv16nkqZttFeqqHjKHmq4QP4kv/).

**Comment by fsdiogo** [comment]
Thanks for reporting @lidel, I was truncating the filenames before, but after adding the link to the IPFS gateways the structure changed and I forgot to refactor that bit. I'll fix it in a moment!
