### ISSUE TITLE
No link to GitHub repo on website :(

### ISSUE THREAD

**Issue by mikeal** [ipfs-shipyard/ipfs-share-files#72]
This is a great example app of how to use IPFS, we should link to where you can find the code :)

**Comment by lidel** [comment]
Web UI's left bottom corner looks like this:

> ![2018-12-19--01-06-48](https://user-images.githubusercontent.com/157609/50190664-6f295400-032a-11e9-8c99-2374935313d0.png)

I think at least in the beginning (to make error reporting easier) we could just do the same here.
