### ISSUE TITLE
Getting project back on track   🏗️👨‍🏭

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#75]
This project was not actively maintained and is behind with both infra and IPFS.

Below is a high level overview of absolute minimum that needs to happen to get it back on track cc @autonome @jessicaschilling 

### The CI

Right now this repo uses Jenkins, which was deprecated and replaced by Travis/CircleCI :sparkles: 

  - [x] remove Jenkins config (`ci/`)  and set up CircleCI
    Tip: cid.ipfs.io website config can be used as a template: [multiformats/cid-utils-website/.circleci/config.yml](https://github.com/multiformats/cid-utils-website/blob/master/.circleci/config.yml)
  - [x] update [#deploy](https://github.com/ipfs-shipyard/ipfs-share-files#deploy) instructions in readme
  - (digression) If we want to keep `dev.share.ipfs.io` then it should be backed by `master`, and a new `production` branch should represent `share.ipfs.io`. This way development cycle on GitHub would not impact production.
    - **Update:** done: https://github.com/ipfs-shipyard/ipfs-share-files/pull/76

### The app

Covered with spider webs :spider_web: 

- [x] update all dependencies to latest versions, refactor if needed
- [x] ensure latest js-ipfs and js-ipfs-http-client are used
  - this means some code needs to be refactored because programmatic JS API changed: https://blog.ipfs.io/2020-02-13-js-ipfs-0-41/
- [x] ensure it works with ipfs-companion enabled
- [x] ensure it loads fine from subdomain gateways at `$cid.ipfs.dweb.link` and `share.ipfs.io.ipns.localhost:8080`
  - small error about service worker, but does not impact the app
- [x] ensure it loads fine from ipns:// in Brave (ipns://dev.share.ipfs.io)
  - there was https://github.com/brave/brave-browser/issues/13722 but it won't impact users, as we copy univeral http URL

The above is a bare minimum needed to keep website up to date and useful.

**Comment by jessicaschilling** [comment]
@lidel -- thanks so much for getting this on paper. What's the next step for getting the CI and infra part of this on someone's radar within the core IFPS team? Once that's done, the remaining parts would make an excellent bounty issue.

**Comment by lidel** [comment]
Switched CI setup to CircleCI in https://github.com/ipfs-shipyard/ipfs-share-files/pull/76 and checked off CI part.

Right now [the  build fails](https://circleci.com/gh/ipfs-shipyard/ipfs-share-files/tree/master) but that may be due to old dependencies. I did not dig into it, as the next item in the list,  "update all dependencies to latest versions" may fix it.

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 re hackathon priorities - can we maybe start with this issue, and specifically just initially getting dependencies etc up to date as quickly as possible? I can't even build this locally, but once I can that unblocks me to working on some of the visual stuff in other issues. Thanks!

**Comment by lidel** [comment]
Agree, this is the blocker of entire endeavor (I'm unable to build current codebase in node 14). 

I've looked at the current codebase, and it won't be easy to just swap js-ipfs to the latest version :( 
The project initializes js-ipfs via the deprecated `ipfs-redux-bundle`:

https://github.com/ipfs-shipyard/ipfs-share-files/blob/2e099d8e7bc9b15650e77459197db58008719035/src/bundles/index.js#L2-L13

Potential path for unblocking:

1. Update to the latest `ipfs`  and `is-ipfs`
1. Remove `ipfs-redux-bundle` and replace it with custom one that implements the same [API](https://www.npmjs.com/package/ipfs-redux-bundle#api) but initializes js-ipfs directly
    - We already removed  `ipfs-redux-bundle` a while ago from ipfs-desktop and replaced it with bundle that  internally uses [ipfs-provider](https://github.com/ipfs-shipyard/ipfs-provider)  (https://github.com/ipfs-shipyard/ipfs-webui/pull/1563)
    - For MVP there is no need for supporting other backends than js-ipfs (`ipfs`), so drop-in replacement bundle can initialize js-ipfs  directly, if that's easier/faster
1. Go over places that operate on ipfs API and refactor where necessary (various IPFS APIs  and tooling like ipfsd-ctl moved from clalbacks to async/away)

@rafaelramalho19 are you willing to give it a try? If you write a drop-in replacement bundle that implements the same [API](https://www.npmjs.com/package/ipfs-redux-bundle#api) as ipfs-redux-bundle, I can help with the remaining API and tests refactor, where needed.

**Comment by jessicaschilling** [comment]
@lidel Can you please look through this checklist again and for things that don't look like they'll get done during hack week, break into separate labeled issues? Thanks 🙏

**Comment by lidel** [comment]
All good!
