### ISSUE TITLE
allow fully display share link for support chrome://flags/#sharing-qr-code-generator

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-share-files#77]
**Is your feature request related to a problem? Please describe.**

allow fully display share link for support `chrome://flags/#sharing-qr-code-generator`

![image](https://user-images.githubusercontent.com/167966/102025531-91e48b00-3dd3-11eb-8010-035ac3494a50.png)

this feature only support when select, but share link is truncate, so we can't select fully link text

![image](https://user-images.githubusercontent.com/167966/102025462-010daf80-3dd3-11eb-8933-0ce5c82a8189.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jessicaschilling** [comment]
Thanks, @bluelovers - we are somewhat slammed at the moment, but would very much welcome any contribution if you or anyone else is interested in working on a PR!

**Comment by jessicaschilling** [comment]
@bluelovers We're actually adding QR support directly in the app, so closing this in favor of https://github.com/ipfs-shipyard/ipfs-share-files/pull/102.
