### ISSUE TITLE
create qr code for share link

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-share-files#78]
**Is your feature request related to a problem? Please describe.**

create qr code for share link, so we can easy scan qr code for open link on other devices

![image](https://user-images.githubusercontent.com/167966/102025577-dc660780-3dd3-11eb-9f84-52c8cded9d8a.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jessicaschilling** [comment]
Thanks, @bluelovers - there's a related request in https://github.com/ipfs-shipyard/ipfs-webui/issues/1358 as well, for Web UI.
We are somewhat slammed at the moment, but would very much welcome any contribution if you or anyone else is interested in working on a PR!
