### ISSUE TITLE
Add language picker and "add translations" callout

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#81]
WebUI automatically detects locale based on request headers, but there is also UI for user to manually change locale.

(there is a bunch of complete translations at Transifex waiting to be used: https://www.transifex.com/ipfs/ipfs-share-files/)

We should also add a "translate this!" prompt to get more translations.

**Comment by jessicaschilling** [comment]
I'd suggest an icon-driven select menu like this one, positioned at bottom left next to the copyright line:
![image](https://user-images.githubusercontent.com/1507828/105518139-25dc2900-5c95-11eb-8840-f3513841f0c5.png)
