### ISSUE TITLE
Smarter Download Button

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-share-files#90]
Right now  Download always downloads .tar archive with all shared files.

This is cool for directories and multiple files, but annoying when a single file is shared.
In that case there is no need to wrap single file in an archive – user should fetch it directly.

I think we should detect when only one file is shared, and make  it either (TBD):
- do the download via `ipfs.cat`
- link  to it directly with `https://ipfs.io/ipfs/{cid}?filename={name}&download=true` parameter, which will trigger download via `content-disposition` HTTP header
  -  I've added it in https://github.com/ipfs/go-ipfs/pull/7677 – will ship in go-ipfs 0.8.0, but is already running on our gateway so safe to use.

**Comment by rafaelramalho19** [comment]
This doesn't work for images, it just opens the image in the browser instead of downloading it. Is it supposed to?
